code live and update

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -14,37 +14,37 @@ jobs:
         node-version: [18.x]
 
     steps:
-      - name: Preserve uploads directory
-        run: |
-          mkdir -p /tmp/uploads_backup
-          tar -czf /tmp/uploads_backup/uploads_backup.tar.gz uploads
+      # - name: Preserve uploads directory
+      #   run: |
+      #     mkdir -p /tmp/uploads_backup
+      #     tar -czf /tmp/uploads_backup/uploads_backup.tar.gz uploads
 
-      - name: Verify backup file creation
-        run: |
-          if [ -f /tmp/uploads_backup/uploads_backup.tar.gz ]; then
-            echo "Backup file created successfully.";
-          else
-            echo "Backup file creation failed.";
-            exit 1;
-          fi
+      # - name: Verify backup file creation
+      #   run: |
+      #     if [ -f /tmp/uploads_backup/uploads_backup.tar.gz ]; then
+      #       echo "Backup file created successfully.";
+      #     else
+      #       echo "Backup file creation failed.";
+      #       exit 1;
+      #     fi
 
       - uses: actions/checkout@v4
 
-      - name: Restore uploads directory
-        run: |
-          if [ -f /tmp/uploads_backup/uploads_backup.tar.gz ]; then
-            tar -xzf /tmp/uploads_backup/uploads_backup.tar.gz;
-            echo "Uploads directory restored successfully.";
-            rm /tmp/uploads_backup/uploads_backup.tar.gz;
-          else
-            echo "Uploads backup file not found. Restore failed.";
-            exit 1;
-          fi
+      # - name: Restore uploads directory
+      #   run: |
+      #     if [ -f /tmp/uploads_backup/uploads_backup.tar.gz ]; then
+      #       tar -xzf /tmp/uploads_backup/uploads_backup.tar.gz;
+      #       echo "Uploads directory restored successfully.";
+      #       rm /tmp/uploads_backup/uploads_backup.tar.gz;
+      #     else
+      #       echo "Uploads backup file not found. Restore failed.";
+      #       exit 1;
+      #     fi
 
-      - name: Clean up all backup files
-        run: |
-          find / -name uploads_backup.tar.gz -exec rm -f {} \;
-          echo "All backup files removed."
+      # - name: Clean up all backup files
+      #   run: |
+      #     find / -name uploads_backup.tar.gz -exec rm -f {} \;
+      #     echo "All backup files removed."
 
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
